import { Module } from '@nestjs/common';
import { ConfigModule, ConfigService } from '@nestjs/config';
import { BullModule } from '@nestjs/bullmq';
import { HealthModule } from './health/health.module';
import { MetricModule } from './metric/metric.module';
import { WorkerConfigModule } from './config/config.module';
import { DatabaseModule } from './database/database.module';
import { CoreExtensionModule } from '@tentacrawl/core';

// generated by @tentacrawl/cli
let workerModules: import('@nestjs/common').DynamicModule[] = [];
try {
  workerModules = require('./generated/modules').workerModules;
} catch {
  // no generated modules yet — run `pnpm generate` to create them
}

@Module({
  imports: [
    ConfigModule.forRoot({
      isGlobal: true,
      envFilePath: ['.env.local', '.env'],
    }),
    BullModule.forRootAsync({
      useFactory: (configService: ConfigService) => ({
        connection: {
          host: configService.get('REDIS_HOST', 'localhost'),
          port: configService.get<number>('REDIS_PORT', 6379),
          password: configService.get('REDIS_PASSWORD') || undefined,
        },
      }),
      inject: [ConfigService],
    }),
    WorkerConfigModule,
    DatabaseModule,
    CoreExtensionModule,
    HealthModule,
    MetricModule,
    ...workerModules,
  ],
})
export class WorkerModule {}
