import { Module, Global } from '@nestjs/common';
import { MikroOrmModule } from '@mikro-orm/nestjs';
import { ConfigService } from '@nestjs/config';
import { ALL_ENTITIES } from '@tentacrawl/core/entity';
import type { EntityClass } from '@mikro-orm/core';

// generated by @tentacrawl/cli
let MODULE_ENTITIES: EntityClass<any>[] = [];
try {
  MODULE_ENTITIES = require('../generated/entities').MODULE_ENTITIES;
} catch {
  // no generated entities yet
}

@Global()
@Module({
  imports: [
    MikroOrmModule.forRootAsync({
      useFactory: (configService: ConfigService) => ({
        driver: require('@mikro-orm/mongodb').MongoDriver,
        clientUrl: configService.getOrThrow<string>('MONGO_URI'),
        dbName: configService.get('MONGO_DB_NAME', 'tentacrawl'),
        entities: [...ALL_ENTITIES, ...MODULE_ENTITIES],
        allowGlobalContext: true,
      }),
      inject: [ConfigService],
    }),
  ],
})
export class DatabaseModule {}
